version: '3'

services:

  sql_influx:
    container_name: sql_influx
    build: ./sql_influx
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PIHOLE_FTL_DB=/etc/pihole/pihole-FTL.db
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    depends_on:
      - influxdb
    networks:
      - influxdb
    volumes:
      - /etc/pihole/:/etc/pihole
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    command: --config-directory /etc/telegraf/telegraf.d
    environment:
      - PIHOLE_API_URL=http://pi.hole/admin/api.php
    depends_on:
      - influxdb
    networks:
      - influxdb
    volumes:
      - ./telegraf:/etc/telegraf
    restart: always

  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    networks:
      influxdb:
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  influxdb:
